---
title: "Resultados_Cluster"
output: html_document
---

#Pacotes necessários

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(data.table)
library(broom)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(knitr)
library(DT)
library(readxl)
library(cleangeo)
library(dplyr)
library(Rtsne) #plot do pam
library(corrplot)
library(gridExtra)
#Pacotes clusterizacao
library(skimr) # Summary statistics
library(mclust) # Model based clustering
library(cluster) # Cluster analysis
library(factoextra) # Visualizing distances
library(hopkins)#analise de tendencia de cluster
library(NbClust)
library(fpc)
library(kamila)

#pacotes de mapa
library(geobr) 
library(plotly)
library(tmap)
library(spData)
library(leaflet)
library(sf)
library(lwgeom)
library(clValid)


#notacao cientifica
options(scipen=999)
setwd("C:/Users/gilma/OneDrive/Área de Trabalho/2022/Master project/Dados Pesquisa")


```

# Abrindo os arquivos

```{r message=FALSE, warning=FALSE, echo=FALSE}
#Abrir arquivo final dos dados municipais
clust_kmeans<-read_delim("outputs2024/kmeans_2024_v3.csv", delim=";",locale=locale(encoding='utf8',decimal_mark = ","))%>%
  data.frame()
```

##Dados Geospaciais##
```{r}
#lendo arquivo geográfico - pacote geobr
mun_BR <- read_municipality(code_muni="all", year=2022)%>%
  select(code_muni)
estados<-read_state(code_state = "all",year=2020)
```

#junção espacial
```{r}
#junção ao espacial
mun_BR<-mun_BR%>%left_join(clust_kmeans,by=c("code_muni"="Cod_municipio"))
#remoção NA
mun_BR <- drop_na(mun_BR)

#organização dos dados 
mun_BR<-mun_BR%>%arrange(cluster,code_muni)

write_sf(mun_BR, "outputs2024/cluster_2024.shp")

# k-means com k=7
Mapa2_kmeans<-tm_shape(mun_BR3) +
    tm_polygons(c("km7"), 
           palette="Spectral",
           style="cat",
           lwd=NA,
               popup.vars = "name_muni.x",
            title=c("kmeans k=7", outer=NA)) +
tm_legend(legend.format = list(text.separator= "a"))+
tm_layout(legend.position = c("LEFT","BOTTOM"),
           title = c("kmeans k=7"))+
  tmap_mode("view")+
tm_basemap(NULL)+    
  tm_shape(estados)+
  tm_borders()

Mapa2_kmeans


Mapa3_kmeans<-tm_shape(mun_BR3) +
    tm_polygons(c("km7"), 
           palette="Spectral",
           style="cat",
           lwd=NA,
           title=c("kmeans k=7", outer=NA)) +
tm_legend(legend.format = list(text.separator= "a"))+
tm_layout(legend.position = c("LEFT","BOTTOM"),
           title = c("kmeans k=7"))

Mapa3_kmeans

# Salvando o mapa como PNG
tmap_save(Mapa3_kmeans, "Mapa3_kmeans.png", width = 1920, height = 1080)

```

#BOX-PLOTS#
## Visualizando os resultados Kmeans
```{r}

#Resultados aglomerados por estado e região
clust_kmeans<- clust_kmeans%>%
  mutate(km7 = as.factor(km7))



 #Gráfico basico
clust_kmeans%>% 
  ggplot()+
  geom_bar(aes(x=km7))+
  ggtitle("Número de municípios por cluster")



  

 #Box plot agsn
clust_kmeans%>%  
  ggplot()+
  geom_boxplot(aes(x=km7, y=PER_AGSN,fill = km7))+
  ggtitle("Percentual de domicílios em Favelas e Comunidades Urbanas" )+
  xlab("Clusters")+
  ylab("Percentual(%) de domicílios em Favelas e Comunidades Urbana")

agsn<-clust_kmeans %>%
  ggplot() +
  geom_boxplot(aes(x = km7, y = PER_AGSN, fill = km7)) +
  ggtitle("Percentual de domicílios em Favelas e Comunidades Urbanas") +
  xlab("Clusters") +
  ylab("Percentual(%) de domicílios em Favelas e Comunidades Urbanas") +
  scale_fill_manual(values = c(
    "1" = "#66c2a5", 
    "2" = "#a6d854", 
    "3" = "#8da0cb", 
    "4" = "#e78ac3", 
    "5" = "#fc8d62", 
    "6" = "#ffd92f", 
    "7" = "#b3b3b3"
  ))
ggsave("outputs2024/graficos_cluster/grafico_agsn.png", plot = agsn, width = 10, height = 6, dpi = 300)
 
#Box plot slope mean
slope<-clust_kmeans%>%  
  ggplot()+
  geom_boxplot(aes(x=km7, y=slope_mean,fill = km7))+
  ggtitle("Declividade média do município" )+
  xlab("Clusters")+
  ylab("Declividade média do município")+
  scale_fill_manual(values = c(
    "1" = "#66c2a5", 
    "2" = "#a6d854", 
    "3" = "#8da0cb", 
    "4" = "#e78ac3", 
    "5" = "#fc8d62", 
    "6" = "#ffd92f", 
    "7" = "#b3b3b3"
  ))
ggsave("outputs2024/graficos_cluster/grafico_slope.png", plot = slope, width = 10, height = 6, dpi = 300)

 #Box plot contiguidade
contig<-clust_kmeans%>%  
  ggplot()+
  geom_boxplot(aes(x=km7, y=contig,fill = km7))+
  ggtitle("Contiguidade da área urbanizada do município" )+
  xlab("Clusters")+
  ylab("Contiguidade da área urbanizada do município")+
  scale_fill_manual(values = c(
    "1" = "#66c2a5", 
    "2" = "#a6d854", 
    "3" = "#8da0cb", 
    "4" = "#e78ac3", 
    "5" = "#fc8d62", 
    "6" = "#ffd92f", 
    "7" = "#b3b3b3"
  ))
ggsave("outputs2024/graficos_cluster/grafico_contig.png", plot = contig, width = 10, height = 6, dpi = 300)

 #Box plot densidade de intersecções
int<-clust_kmeans%>%  
  ggplot()+
  geom_boxplot(aes(x=km7, y=dens_int_au,fill = km7))+
  ggtitle("Densidade de intersecções viárias da área urbanizada do município" )+
  xlab("Clusters")+
  ylab("Densidade de intersecções viárias da área urbanizada do município")+
  scale_fill_manual(values = c(
    "1" = "#66c2a5", 
    "2" = "#a6d854", 
    "3" = "#8da0cb", 
    "4" = "#e78ac3", 
    "5" = "#fc8d62", 
    "6" = "#ffd92f", 
    "7" = "#b3b3b3"
  ))
ggsave("outputs2024/graficos_cluster/grafico_int.png", plot = int, width = 10, height = 6, dpi = 300)

#Grafico área km2
 areakm<-clust_kmeans%>%  
  ggplot()+
  geom_boxplot(aes(x=km7, y=AREA_KM2,fill = km7),
               outlier.shape = 16,  # Muda a forma dos outliers para pontos
               outlier.size = 1,    # Diminui o tamanho dos outliers
               size=0.1)+   #espessura linha
   ggtitle("Área em quilômetros quadrados do limite municipal" )+
  xlab("Clusters")+
  ylab("Área em quilômetros quadrados do limite municipal")+
  scale_fill_manual(values = c(
    "1" = "#66c2a5", 
    "2" = "#a6d854", 
    "3" = "#8da0cb", 
    "4" = "#e78ac3", 
    "5" = "#fc8d62", 
    "6" = "#ffd92f", 
    "7" = "#b3b3b3"
  ))
ggsave("outputs2024/graficos_cluster/grafico_area.png", plot = areakm, width = 10, height = 6, dpi = 300)

 #Box plot número de desastres
des<-clust_kmeans%>%  
  ggplot()+
  geom_boxplot(aes(x=km7, y=numero_desastres_p,fill = km7),
               outlier.shape = 16,  # Muda a forma dos outliers para pontos
               outlier.size = 1,    # Diminui o tamanho dos outliers
               size=0.1)+   #espessura linha
   ggtitle("Número de desastres hidrológicos de 2012 a 2023" )+
  xlab("Clusters")+
  ylab("Número de desastres hidrológicos de 2012 a 2023")+
  scale_fill_manual(values = c(
    "1" = "#66c2a5", 
    "2" = "#a6d854", 
    "3" = "#8da0cb", 
    "4" = "#e78ac3", 
    "5" = "#fc8d62", 
    "6" = "#ffd92f", 
    "7" = "#b3b3b3"
  ))
ggsave("outputs2024/graficos_cluster/grafico_des.png", plot = des, width = 10, height = 6, dpi = 300)


 #Box plot população - todos
pop_t<-clust_kmeans%>%  
  ggplot()+
  geom_boxplot(aes(x=km7, y=POP2022,fill = km7),
               outlier.shape = 16,  # Muda a forma dos outliers para pontos
               outlier.size = 1,    # Diminui o tamanho dos outliers
               size=0.1)+   #espessura linha
   ggtitle("População (Censo 2022)" )+
  xlab("Clusters")+
  ylab("População (Censo 2022)")+
  scale_fill_manual(values = c(
    "1" = "#66c2a5", 
    "2" = "#a6d854", 
    "3" = "#8da0cb", 
    "4" = "#e78ac3", 
    "5" = "#fc8d62", 
    "6" = "#ffd92f", 
    "7" = "#b3b3b3"
  ))
ggsave("outputs2024/graficos_cluster/grafico_popt.png", plot = pop_t, width = 10, height = 6, dpi = 300)

 #Box plot população - sem são paulo e sem outliers
pop<-clust_kmeans %>%
  filter(km7!="5")%>%
  ggplot() +
  geom_boxplot(aes(x = km7, y = POP2022, fill = km7),
                outlier.shape = NA,  # Muda a forma dos outliers para pontos
                          size=0.1)+
  ggtitle("População (Censo 2022)") +
  xlab("Clusters") +
  ylab("População (Censo 2022)") +
  scale_y_continuous(labels = scales::comma, 
                     limits = c(0, 2000000),  # Definindo o limite máximo
                     breaks = seq(0, 12000000, by = 100000))+
  scale_fill_manual(values = c(
    "1" = "#66c2a5", 
    "2" = "#a6d854", 
    "3" = "#8da0cb", 
    "4" = "#e78ac3", 
    "5" = "#fc8d62", 
    "6" = "#ffd92f", 
    "7" = "#b3b3b3"
  ))
ggsave("outputs2024/graficos_cluster/grafico_pop.png", plot = pop, width = 10, height = 6, dpi = 300)  # Intervalos customizados


#
# Convertendo todas as variáveis para numeric
data <- clust_kmeans %>%select("PER_AGSN", "slope_mean", "contig", 
                  "dens_int_au", "AREA_KM2", "numero_desastres_p", 
                  "POP2022", "km7")%>%
  mutate(across(c("PER_AGSN", "slope_mean", "contig", 
                  "dens_int_au", "AREA_KM2", "numero_desastres_p", 
                  "POP2022"), 
                as.numeric))

# Aplicando o pivot_longer após a conversão
data_long <- data %>%
  pivot_longer(cols = c("PER_AGSN", "slope_mean", "contig", 
                        "dens_int_au", "AREA_KM2", "numero_desastres_p", 
                        "POP2022"),
               names_to = "Variable",
               values_to = "Value")

# Criando o boxplot
ggplot(data_long, aes(x = km7, y = Value, fill = km7)) +
  geom_boxplot() +
  facet_wrap(~ Variable, scales = "free_y") +
  theme_minimal() +
  labs(title = "Boxplots por cluster",
       x = "km7",
       y = "Valor") +
  theme(legend.position = "none")


```

